spring:
  datasource:
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
mybatis:
  config-location: classpath:/mybatis/SqlMapConfig.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml